export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAIULURE';
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_FAILURE = 'ADD_AUTHOR_FAILURE';
